version: "3"

services:

  home-ip-registry:
    build: .
    ports:
      - 5005:5005
      - 8000:8000
    environment:
      SERVER_ADDRESS: "0.0.0.0"
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/.ivy2:/root/.ivy2"
      - ".:/opt/home-ip-registry"
      - "/opt/home-ip-registry/target"
      - "/opt/home-ip-registry/project/target"